# -*- coding: utf-8 -*-
"""EIDS_RandomForrest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NdglocVQ7cpx0tsZFmPGwV_aQihaqCO2
"""

import pandas as pd
import numpy as np

# Load the uploaded CSV files
features_df = pd.read_csv("/content/EEDS_features_v2.csv")
metadata_df = pd.read_csv("/content/metadata.csv")

print("Features shape:", features_df.shape)
print("Metadata shape:", metadata_df.shape)

print("\nFeatures columns:")
print(features_df.columns.tolist())

print("\nMetadata columns:")
print(metadata_df.columns.tolist())

print("FEATURE DATA")
display(features_df.head())

print("\nMETADATA")
display(metadata_df.head())

# Remove possible whitespace from column names
features_df.columns = features_df.columns.str.strip()
metadata_df.columns = metadata_df.columns.str.strip()

# Compare filenames
feature_files = features_df["File"].astype(str).str.strip()
metadata_files = (
    metadata_df["file"]
    .astype(str)
    .str.strip()
    .str.split("/")
    .str[-1]
)

# Compare classes
feature_classes = features_df["Class"].astype(str).str.strip().str.lower()
metadata_classes = metadata_df["class_name"].astype(str).str.strip().str.lower()

print("Number of feature samples :", len(features_df))
print("Number of metadata samples:", len(metadata_df))

print("\nFilename matches:",
      (feature_files.values == metadata_files.values).sum(),
      "/", len(features_df))

print("Class matches:",
      (feature_classes.values == metadata_classes.values).sum(),
      "/", len(features_df))

print("Class distribution:")
print(features_df["Class"].value_counts())

print("\nUnique classes:")
print(features_df["Class"].unique())

selected_features = [
    "CH1_STA_LTA",
    "CH1_RMS",
    "CH1_ZCR",
    "CH1_Predominant_Frequency",

    "CH2_STA_LTA",
    "CH2_RMS",
    "CH2_ZCR",
    "CH2_Predominant_Frequency",

    "CH3_STA_LTA",
    "CH3_RMS",
    "CH3_ZCR",
    "CH3_Predominant_Frequency"
]

X = features_df[selected_features].copy()
y = features_df["Class"].copy()

print("Selected features:", len(selected_features))
print("X shape:", X.shape)
print("y shape:", y.shape)

display(X.head())

# Check whether feature rows and metadata rows have the same class
# and inspect filename correspondence by class.

print("Filename matching by class:\n")

for cls in ["elephant", "human", "bovid", "noise"]:

    f_files = features_df[
        features_df["Class"].str.lower() == cls
    ]["File"].astype(str).str.strip()

    m_files = metadata_df[
        metadata_df["class_name"].str.lower() == cls
    ]["file"].astype(str).str.strip().str.split("/").str[-1]

    matches = (f_files.values == m_files.values).sum()

    print(f"{cls:10s}: {matches} / {len(f_files)} filename matches")

print("\nFeature and metadata class agreement:")

comparison = pd.DataFrame({
    "Feature_Class": features_df["Class"].astype(str).str.lower(),
    "Metadata_Class": metadata_df["class_name"].astype(str).str.lower()
})

print(comparison.value_counts())

# Check for missing and infinite values

print("=== Missing Values ===")
missing = X.isnull().sum()
print(missing)

print("\nTotal missing values:", missing.sum())

print("\n=== Infinite Values ===")
infinite_count = np.isinf(X.to_numpy()).sum()
print("Total infinite values:", infinite_count)

# Statistical summary of the 12 selected features

feature_stats = X.describe().T

feature_stats["range"] = (
    feature_stats["max"] - feature_stats["min"]
)

display(
    feature_stats[
        ["mean", "std", "min", "max", "range"]
    ]
)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples :", len(X_test))

print("\nTraining class distribution:")
print(y_train.value_counts())

print("\nTesting class distribution:")
print(y_test.value_counts())

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    max_features="sqrt",
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

print("Random Forest training completed.")
print("Number of trees:", rf_model.n_estimators)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

# Predictions
y_pred = rf_model.predict(X_test)

# Metrics
accuracy = accuracy_score(y_test, y_pred)

precision = precision_score(
    y_test,
    y_pred,
    average="weighted"
)

recall = recall_score(
    y_test,
    y_pred,
    average="weighted"
)

f1 = f1_score(
    y_test,
    y_pred,
    average="weighted"
)

print("=" * 55)
print("           EEDS RANDOM FOREST RESULTS")
print("=" * 55)

print(f"Accuracy  : {accuracy:.4f} ({accuracy * 100:.2f}%)")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1-score  : {f1:.4f}")

print("\n" + "=" * 55)
print("CLASSIFICATION REPORT")
print("=" * 55)

print(classification_report(
    y_test,
    y_pred,
    digits=4
))

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm = confusion_matrix(
    y_test,
    y_pred,
    labels=rf_model.classes_
)

print("Confusion Matrix:")
print(cm)

fig, ax = plt.subplots(figsize=(7, 6))

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=rf_model.classes_
)

disp.plot(
    ax=ax,
    values_format="d"
)

ax.set_title("EEDS Random Forest Confusion Matrix")
ax.set_xlabel("Predicted Class")
ax.set_ylabel("Actual Class")

plt.tight_layout()
plt.show()

# Random Forest feature importance

importance_df = pd.DataFrame({
    "Feature": selected_features,
    "Importance": rf_model.feature_importances_
})

importance_df = importance_df.sort_values(
    by="Importance",
    ascending=False
).reset_index(drop=True)

print("Feature Importance:")
display(importance_df)

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 7))

plt.barh(
    importance_df["Feature"],
    importance_df["Importance"]
)

plt.xlabel("Random Forest Importance")
plt.ylabel("Feature")
plt.title("EEDS Random Forest Feature Importance")

plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

feature_groups = {
    "STA/LTA": [
        "CH1_STA_LTA",
        "CH2_STA_LTA",
        "CH3_STA_LTA"
    ],
    "RMS": [
        "CH1_RMS",
        "CH2_RMS",
        "CH3_RMS"
    ],
    "ZCR": [
        "CH1_ZCR",
        "CH2_ZCR",
        "CH3_ZCR"
    ],
    "Predominant Frequency": [
        "CH1_Predominant_Frequency",
        "CH2_Predominant_Frequency",
        "CH3_Predominant_Frequency"
    ]
}

group_importance = {}

for group, feature_list in feature_groups.items():
    group_importance[group] = importance_df[
        importance_df["Feature"].isin(feature_list)
    ]["Importance"].sum()

group_importance_df = pd.DataFrame(
    list(group_importance.items()),
    columns=["Feature Type", "Total Importance"]
).sort_values(
    by="Total Importance",
    ascending=False
)

print("Overall Feature-Type Importance:")
display(group_importance_df)

# ============================================
# BLOCK 17: 5-FOLD STRATIFIED CROSS-VALIDATION
# ============================================

from sklearn.model_selection import StratifiedKFold, cross_val_score
import numpy as np

# Create 5 stratified folds
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

# Evaluate the baseline Random Forest using cross-validation
cv_scores = cross_val_score(
    rf_model,
    X,
    y,
    cv=cv,
    scoring="accuracy",
    n_jobs=-1
)

print("=" * 55)
print("EEDS RANDOM FOREST - 5-FOLD CROSS-VALIDATION")
print("=" * 55)

for i, score in enumerate(cv_scores, start=1):
    print(f"Fold {i} Accuracy: {score:.4f} ({score * 100:.2f}%)")

print("-" * 55)
print(f"Mean Accuracy: {np.mean(cv_scores):.4f} "
      f"({np.mean(cv_scores) * 100:.2f}%)")

print(f"Standard Deviation: {np.std(cv_scores):.4f}")
print("=" * 55)

# ============================================
# BLOCK 18: RANDOM FOREST HYPERPARAMETER TUNING
# ============================================

from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from scipy.stats import randint

# Cross-validation performed only on the training data
tuning_cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

# Hyperparameter search space
param_distributions = {
    "n_estimators": randint(200, 801),
    "max_depth": [None, 10, 15, 20, 30, 40],
    "min_samples_split": randint(2, 11),
    "min_samples_leaf": randint(1, 5),
    "max_features": ["sqrt", "log2", None],
    "class_weight": [
        None,
        "balanced",
        "balanced_subsample"
    ]
}

# Base Random Forest model
rf_base = RandomForestClassifier(
    random_state=42,
    n_jobs=-1
)

# Randomized hyperparameter search
rf_tuned_train = RandomizedSearchCV(
    estimator=rf_base,
    param_distributions=param_distributions,
    n_iter=30,
    scoring="f1_macro",
    cv=tuning_cv,
    verbose=1,
    random_state=42,
    n_jobs=-1,
    refit=True
)

# IMPORTANT:
# Tune only on the training dataset.
# X_test and y_test remain untouched.
rf_tuned_train.fit(X_train, y_train)

print("=" * 60)
print("RANDOM FOREST HYPERPARAMETER TUNING COMPLETED")
print("=" * 60)

print("\nBest Hyperparameters:")
print(rf_tuned_train.best_params_)

print("\nBest Cross-Validation Macro F1-Score:")
print(f"{rf_tuned_train.best_score_:.4f}")

# ============================================
# BLOCK 19: EVALUATION OF THE TUNED RANDOM FOREST
# ============================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)
import matplotlib.pyplot as plt

# Predict using the tuned model
y_pred_tuned = rf_tuned_train.predict(X_test)

# Calculate evaluation metrics
accuracy_tuned = accuracy_score(y_test, y_pred_tuned)

precision_tuned = precision_score(
    y_test,
    y_pred_tuned,
    average="weighted",
    zero_division=0
)

recall_tuned = recall_score(
    y_test,
    y_pred_tuned,
    average="weighted",
    zero_division=0
)

f1_tuned = f1_score(
    y_test,
    y_pred_tuned,
    average="weighted",
    zero_division=0
)

print("=" * 60)
print("EEDS TUNED RANDOM FOREST RESULTS")
print("=" * 60)

print(f"Accuracy:  ️{accuracy_tuned:.4f} "
      f"({accuracy_tuned * 100:.2f}%)")

print(f"Precision: {precision_tuned:.4f}")
print(f"Recall:    {recall_tuned:.4f}")
print(f"F1-score:  {f1_tuned:.4f}")

print("\n" + "=" * 60)
print("CLASSIFICATION REPORT")
print("=" * 60)

print(
    classification_report(
        y_test,
        y_pred_tuned,
        digits=4,
        zero_division=0
    )
)

# Confusion matrix
cm_tuned = confusion_matrix(
    y_test,
    y_pred_tuned,
    labels=rf_tuned_train.classes_
)

print("\nConfusion Matrix:")
print(cm_tuned)

# Display confusion matrix
fig, ax = plt.subplots(figsize=(7, 6))

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_tuned,
    display_labels=rf_tuned_train.classes_
)

disp.plot(
    ax=ax,
    values_format="d"
)

ax.set_title("EEDS Tuned Random Forest Confusion Matrix")
plt.tight_layout()
plt.show()

# ============================================
# BLOCK 20: BASELINE VS TUNED MODEL COMPARISON
# ============================================

import pandas as pd

comparison_df = pd.DataFrame({
    "Metric": [
        "Accuracy",
        "Weighted Precision",
        "Weighted Recall",
        "Weighted F1-Score"
    ],
    "Baseline Random Forest": [
        accuracy,
        precision,
        recall,
        f1
    ],
    "Tuned Random Forest": [
        accuracy_tuned,
        precision_tuned,
        recall_tuned,
        f1_tuned
    ]
})

# Calculate the difference
comparison_df["Difference"] = (
    comparison_df["Tuned Random Forest"]
    - comparison_df["Baseline Random Forest"]
)

print("=" * 70)
print("EEDS BASELINE VS TUNED RANDOM FOREST")
print("=" * 70)

display(comparison_df)

print("\nInterpretation:")
if accuracy_tuned > accuracy:
    print("The tuned model improved test accuracy.")
elif accuracy_tuned < accuracy:
    print("The baseline model achieved higher test accuracy.")
else:
    print("Both models achieved the same test accuracy.")

# ============================================
# BLOCK 21: SAVE THE SELECTED RANDOM FOREST MODEL
# ============================================

import joblib
import json
import os

# Create a folder for the saved model
model_dir = "/content/EEDS_RF_Model"
os.makedirs(model_dir, exist_ok=True)

# Save the baseline Random Forest model
model_path = os.path.join(
    model_dir,
    "EEDS_RandomForest_Baseline.pkl"
)

joblib.dump(rf_model, model_path)

# Save the selected feature names
feature_path = os.path.join(
    model_dir,
    "EEDS_selected_features.json"
)

with open(feature_path, "w") as f:
    json.dump(selected_features, f, indent=4)

# Save additional model information
model_info = {
    "model_name": "EEDS Baseline Random Forest",
    "algorithm": "Random Forest Classifier",
    "n_estimators": rf_model.n_estimators,
    "max_depth": rf_model.max_depth,
    "max_features": rf_model.max_features,
    "min_samples_split": rf_model.min_samples_split,
    "min_samples_leaf": rf_model.min_samples_leaf,
    "class_weight": rf_model.class_weight,
    "random_state": rf_model.random_state,
    "selected_features": selected_features,
    "number_of_features": len(selected_features),
    "training_samples": len(X_train),
    "testing_samples": len(X_test),
    "test_accuracy": float(accuracy),
    "test_weighted_precision": float(precision),
    "test_weighted_recall": float(recall),
    "test_weighted_f1_score": float(f1)
}

info_path = os.path.join(
    model_dir,
    "EEDS_model_info.json"
)

with open(info_path, "w") as f:
    json.dump(model_info, f, indent=4)

print("=" * 60)
print("EEDS RANDOM FOREST MODEL SAVED SUCCESSFULLY")
print("=" * 60)

print(f"Model file:    {model_path}")
print(f"Feature file:  {feature_path}")
print(f"Info file:     {info_path}")

# ============================================
# BLOCK 22: PACKAGE EEDS MODEL FILES
# ============================================

import shutil
import os

model_dir = "/content/EEDS_RF_Model"
zip_path = "/content/EEDS_RF_Model"

# Create ZIP archive
shutil.make_archive(
    base_name=zip_path,
    format="zip",
    root_dir=model_dir
)

final_zip = "/content/EEDS_RF_Model.zip"

print("=" * 60)
print("EEDS MODEL PACKAGE CREATED SUCCESSFULLY")
print("=" * 60)
print(f"ZIP file: {final_zip}")

# Display files inside the model directory
print("\nFiles included:")
for filename in os.listdir(model_dir):
    print("-", filename)

# ============================================
# BLOCK 23A: SLIDING-WINDOW RF PREDICTION
# ============================================

import os
import json
import glob
import joblib
import numpy as np
import pandas as pd

# ============================================
# CONFIGURATION
# ============================================

SAMPLE_RATE = 200
WINDOW_SIZE = 2045

# Use a 1-second step between windows
STEP_SIZE = SAMPLE_RATE

MODEL_PATH = "/content/EEDS_RF_Model/EEDS_RandomForest_Baseline.pkl"

selected_features = [
    "CH1_STA_LTA",
    "CH1_RMS",
    "CH1_ZCR",
    "CH1_Predominant_Frequency",
    "CH2_STA_LTA",
    "CH2_RMS",
    "CH2_ZCR",
    "CH2_Predominant_Frequency",
    "CH3_STA_LTA",
    "CH3_RMS",
    "CH3_ZCR",
    "CH3_Predominant_Frequency"
]

# ============================================
# LOAD MODEL
# ============================================

rf_model_loaded = joblib.load(MODEL_PATH)

print("Model loaded successfully.")
print("Classes:", rf_model_loaded.classes_)

# ============================================
# FEATURE FUNCTIONS
# ============================================

def calculate_sta_lta(signal, sample_rate=200):
    signal = np.asarray(signal, dtype=float)
    signal = signal - np.mean(signal)

    absolute_signal = np.abs(signal)

    sta_size = max(1, int(sample_rate * 1.0))

    sta_values = np.convolve(
        absolute_signal,
        np.ones(sta_size) / sta_size,
        mode="valid"
    )

    lta_value = np.mean(absolute_signal)

    if lta_value == 0:
        return 0.0

    return float(np.max(sta_values) / lta_value)


def calculate_rms(signal):
    signal = np.asarray(signal, dtype=float)
    signal = signal - np.mean(signal)

    return float(np.sqrt(np.mean(signal ** 2)))


def calculate_zcr(signal):
    signal = np.asarray(signal, dtype=float)
    signal = signal - np.mean(signal)

    return float(np.sum(
        np.diff(np.signbit(signal)) != 0
    ))


def calculate_predominant_frequency(signal, sample_rate=200):
    signal = np.asarray(signal, dtype=float)
    signal = signal - np.mean(signal)

    if np.all(signal == 0):
        return 0.0

    frequencies = np.fft.rfftfreq(
        len(signal),
        d=1 / sample_rate
    )

    spectrum = np.abs(np.fft.rfft(signal))
    spectrum[0] = 0

    dominant_index = np.argmax(spectrum)

    return float(frequencies[dominant_index])


def extract_channel_features(signal):
    return {
        "STA_LTA": calculate_sta_lta(signal, SAMPLE_RATE),
        "RMS": calculate_rms(signal),
        "ZCR": calculate_zcr(signal),
        "Predominant_Frequency":
            calculate_predominant_frequency(signal, SAMPLE_RATE)
    }

# ============================================
# LOAD JSONL DATA
# ============================================

def load_jsonl_recording(file_path):
    vx_values = []
    vy_values = []
    vz_values = []

    timestamps = []
    skipped_lines = 0

    with open(file_path, "r", errors="replace") as file:
        for line in file:
            try:
                record = json.loads(line)

                if "sample" not in record:
                    continue

                if not all(
                    key in record
                    for key in ["vx", "vy", "vz"]
                ):
                    skipped_lines += 1
                    continue

                vx_values.append(float(record["vx"]))
                vy_values.append(float(record["vy"]))
                vz_values.append(float(record["vz"]))

                timestamps.append(
                    record.get("time", None)
                )

            except Exception:
                skipped_lines += 1

    signals = {
        "CH1": np.array(vx_values),
        "CH2": np.array(vy_values),
        "CH3": np.array(vz_values)
    }

    return signals, timestamps, skipped_lines

# ============================================
# EXTRACT SLIDING-WINDOW FEATURES
# ============================================

def extract_sliding_window_features(
    signals,
    timestamps,
    window_size=2045,
    step_size=200
):
    total_samples = len(signals["CH1"])

    rows = []

    for start in range(
        0,
        total_samples - window_size + 1,
        step_size
    ):

        end = start + window_size

        row = {
            "Start_Sample": start,
            "End_Sample": end,
            "Window_Duration_sec": window_size / SAMPLE_RATE
        }

        # Preserve the first and last timestamp in the window
        if timestamps:
            row["Start_Timestamp"] = timestamps[start]
            row["End_Timestamp"] = timestamps[end - 1]

        for channel in ["CH1", "CH2", "CH3"]:

            signal_window = signals[channel][start:end]

            channel_features = extract_channel_features(
                signal_window
            )

            for feature_name, feature_value in channel_features.items():
                row[f"{channel}_{feature_name}"] = feature_value

        rows.append(row)

    return pd.DataFrame(rows)

# ============================================
# PROCESS ALL RECORDINGS
# ============================================

jsonl_files = sorted(
    glob.glob("/content/*.jsonl")
)

if not jsonl_files:
    raise FileNotFoundError(
        "No JSONL recordings found in /content."
    )

all_predictions = []

for file_path in jsonl_files:

    filename = os.path.basename(file_path)

    print("\n" + "=" * 70)
    print("Processing:", filename)
    print("=" * 70)

    signals, timestamps, skipped_lines = load_jsonl_recording(
        file_path
    )

    print("Samples loaded:", len(signals["CH1"]))
    print("Skipped lines:", skipped_lines)

    feature_df = extract_sliding_window_features(
        signals,
        timestamps,
        WINDOW_SIZE,
        STEP_SIZE
    )

    if feature_df.empty:
        print("No complete windows available.")
        continue

    X_real = feature_df[selected_features]

    predictions = rf_model_loaded.predict(X_real)
    probabilities = rf_model_loaded.predict_proba(X_real)

    feature_df["Predicted_Class"] = predictions
    feature_df["Prediction_Confidence"] = np.max(
        probabilities,
        axis=1
    )

    feature_df["Source_File"] = filename

    all_predictions.append(feature_df)

    print("Windows processed:", len(feature_df))
    print("\nPrediction distribution:")
    print(feature_df["Predicted_Class"].value_counts())

# ============================================
# SAVE ALL PREDICTIONS
# ============================================

if all_predictions:

    final_predictions_df = pd.concat(
        all_predictions,
        ignore_index=True
    )

    output_path = (
        "/content/EEDS_real_recording_sliding_predictions.csv"
    )

    final_predictions_df.to_csv(
        output_path,
        index=False
    )

    print("\n" + "=" * 70)
    print("SLIDING-WINDOW TEST COMPLETED")
    print("=" * 70)

    print("Total windows:", len(final_predictions_df))
    print("Output file:", output_path)

    display(final_predictions_df.head(20))

else:
    print("No predictions were generated.")

# ============================================================
# EEDS BLOCK 24
# CORRECTED REAL-RECORDING RANDOM FOREST PREDICTION
# ============================================================

import os
import json
import glob
import joblib
import numpy as np
import pandas as pd

from scipy.signal import welch


# ============================================================
# SETTINGS
# ============================================================

SAMPLE_RATE = 200
WINDOW_SIZE = 2048
STEP_SIZE = 200       # 1-second step

MODEL_PATH = "/content/EEDS_RF_Model/EEDS_RandomForest_Baseline.pkl"
FEATURES_PATH = "/content/EEDS_RF_Model/EEDS_selected_features.json"

OUTPUT_FILE = "/content/EEDS_corrected_real_predictions.csv"


# ============================================================
# LOAD MODEL AND FEATURES
# ============================================================

rf_model = joblib.load(MODEL_PATH)

with open(FEATURES_PATH, "r") as file:
    selected_features = json.load(file)

print("Model loaded successfully")
print("Selected features:")
print(selected_features)


# ============================================================
# EXACT TRAINING FEATURE FUNCTIONS
# ============================================================

def calculate_rms(signal):
    return np.sqrt(np.mean(signal ** 2))


def calculate_zcr(signal):
    crossings = np.sum(
        signal[:-1] * signal[1:] < 0
    )

    duration = len(signal) / SAMPLE_RATE

    return crossings / duration


def calculate_predominant_frequency(signal):
    frequencies, power = welch(
        signal,
        fs=SAMPLE_RATE,
        nperseg=min(512, len(signal))
    )

    if len(power) > 1:
        index = np.argmax(power[1:]) + 1
    else:
        index = np.argmax(power)

    return frequencies[index]


def calculate_sta_lta(signal):
    STA_SECONDS = 0.25
    LTA_SECONDS = 2.0

    STA_SAMPLES = int(STA_SECONDS * SAMPLE_RATE)
    LTA_SAMPLES = int(LTA_SECONDS * SAMPLE_RATE)

    squared = signal ** 2

    sta_values = []

    start = LTA_SAMPLES
    end = len(signal) - STA_SAMPLES

    if end <= start:
        return 0.0

    for i in range(start, end):

        lta_start = i - LTA_SAMPLES
        lta_end = i

        sta_start = i
        sta_end = i + STA_SAMPLES

        lta = np.mean(
            squared[lta_start:lta_end]
        )

        sta = np.mean(
            squared[sta_start:sta_end]
        )

        lta = max(lta, 1e-20)

        ratio = sta / lta

        sta_values.append(ratio)

    if len(sta_values) == 0:
        return 0.0

    return np.max(sta_values)


def extract_channel_features(signal):

    signal = np.asarray(
        signal,
        dtype=np.float64
    )

    return {
        "STA_LTA": calculate_sta_lta(signal),
        "RMS": calculate_rms(signal),
        "ZCR": calculate_zcr(signal),
        "Predominant_Frequency":
            calculate_predominant_frequency(signal)
    }


# ============================================================
# PROCESS ONE JSONL FILE
# ============================================================

def process_jsonl(filepath):

    channel_1 = []
    channel_2 = []
    channel_3 = []
    timestamps = []

    with open(filepath, "r") as file:

        for line_number, line in enumerate(file, start=1):

            try:
                record = json.loads(line)

                # Use the same fields as the previous test
                if not all(
                    key in record
                    for key in ["vx", "vy", "vz"]
                ):
                    continue

                channel_1.append(float(record["vx"]))
                channel_2.append(float(record["vy"]))
                channel_3.append(float(record["vz"]))

                timestamps.append(
                    record.get("time", "")
                )

            except Exception as error:
                print(
                    f"Skipping line {line_number}: {error}"
                )

    channels = [
        np.asarray(channel_1),
        np.asarray(channel_2),
        np.asarray(channel_3)
    ]

    results = []

    if len(channel_1) < WINDOW_SIZE:
        print(
            f"{os.path.basename(filepath)}: "
            f"Not enough samples"
        )
        return results

    for start in range(
        0,
        len(channel_1) - WINDOW_SIZE + 1,
        STEP_SIZE
    ):

        end = start + WINDOW_SIZE

        row = {
            "Source_File": os.path.basename(filepath),
            "Start_Sample": start,
            "End_Sample": end - 1,
            "Start_Time": timestamps[start],
            "End_Time": timestamps[end - 1]
        }

        feature_row = {}

        for channel_index, signal in enumerate(channels, start=1):

            window = signal[start:end]

            features = extract_channel_features(window)

            for feature_name, value in features.items():

                column_name = (
                    f"CH{channel_index}_{feature_name}"
                )

                feature_row[column_name] = value

        # Keep only the model's required features
        model_input = pd.DataFrame(
            [feature_row]
        )[selected_features]

        prediction = rf_model.predict(model_input)[0]

        probabilities = rf_model.predict_proba(
            model_input
        )[0]

        confidence = np.max(probabilities)

        row["Prediction"] = prediction
        row["Confidence"] = confidence

        for class_name, probability in zip(
            rf_model.classes_,
            probabilities
        ):
            row[f"Probability_{class_name}"] = probability

        row.update(feature_row)

        results.append(row)

    return results


# ============================================================
# PROCESS ALL JSONL FILES
# ============================================================

jsonl_files = sorted(
    glob.glob("/content/*.jsonl")
)

all_results = []

print("\nFiles found:", len(jsonl_files))

for filepath in jsonl_files:

    print(
        "\nProcessing:",
        os.path.basename(filepath)
    )

    file_results = process_jsonl(filepath)

    all_results.extend(file_results)

    print(
        "Windows generated:",
        len(file_results)
    )


# ============================================================
# SAVE RESULTS
# ============================================================

if len(all_results) > 0:

    results_df = pd.DataFrame(all_results)

    results_df.to_csv(
        OUTPUT_FILE,
        index=False
    )

    print("\n========================================")
    print("CORRECTED PREDICTION COMPLETE")
    print("========================================")

    print("Total windows:", len(results_df))
    print("Output:", OUTPUT_FILE)

    print("\nPrediction distribution:")
    print(results_df["Prediction"].value_counts())

    print("\nAverage confidence:")
    print(results_df["Confidence"].mean())

    print("\nFirst five predictions:")
    display(results_df.head())

else:

    print("No prediction windows were generated.")